### PR TITLE
#some times the `InfoMessages` maybe null

### PR DESCRIPTION
**Pull request by DUWENINK**
in my test case ,it works for me

### CODE REVIEW

**Comment by FanDjango** [comment]
Ok, I suppose so. Do you have an example or description, just for my curiosity? And then we need to do the same for SYNC client as well?

**Comment by DUWENINK** [comment]
yes ,I am test for muti-thread and the xunit report "Object null reference exception" and I find this

**Comment by DUWENINK** [comment]
yes ,i am test for muti-thread and the xunit report "Object null reference exception" and I find this

**Comment by robinrodricks** [comment]
Small fixes are good. Thanks!

**Comment by FanDjango** [comment]
@robinrodricks and SYNC!?! And the exact circumstances certainly would be interesting? Who knows where else InfoMessages are queried and might also be null?

**Pull request merged**
