### PR TITLE
Reveal CipherSuite in addition to SslProtocol

### PR DESCRIPTION
**Pull request by FanDjango**
```cs
				client.Connect();
				Console.WriteLine("Selected SSL Version/Protocol " + client.SslProtocolActive);
				Console.WriteLine("Selected SSL Ciphersuite " + client.SslCipherSuiteActive);
```
Result:
```
Selected SSL Version/Protocol Tls12
Selected SSL Ciphersuite Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 255)
```

### CODE REVIEW

**Comment by robinrodricks** [comment]
Could we rename this to `SslCipherSuite` ?

**Comment by FanDjango** [comment]
Should we also rename `client.SslProtocolActive` to `client.SslProtocol`?

**Comment by robinrodricks** [comment]
Yes please. I missed out noticing that one.

**Comment by FanDjango** [comment]
Done.

**Pull request merged**
