### PR TITLE
Clean up NET50_OR_LATER -> NET5_0_OR_GREATER

### PR DESCRIPTION
**Pull request by FanDjango**
Follow up to #1389

### CODE REVIEW

**Comment by sean-bloch** [comment]
@FanDjango  a quick followup comment to #1389 I have noticed after looking at more of the code, that there is likely more opportunity to review the intent of some directives and their usage, as seen by the lines in FluentFTP.csproj:

```
 <PropertyGroup Condition="'$(TargetFramework)'=='net50'">
        <DefineConstants>$(DefineConstants);NET50;NETSTANDARD;NET50_OR_LATER;</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)'=='net60'">
        <DefineConstants>$(DefineConstants);NET60;NETSTANDARD;NET50_OR_LATER;</DefineConstants>
    </PropertyGroup>
```

Especially when comparing against documentation for ["Target frameworks in SDK-style projects"](https://learn.microsoft.com/en-us/dotnet/standard/frameworks).

**Comment by FanDjango** [comment]
@sean-bloch LOL - I am working on that right now. I'll put in a PR ASAP for you to look at.

**Comment by sean-bloch** [comment]
Hey cool, I'm really just ripping out things I don't need and making a personal build. But when I wonder about "intent" of some of the legacy `NETSTANDARD` usages, I saw for example in AsyncClient/DownloadFile:
```
#if NETSTANDARD
    else if (existsMode == FtpLocalExists.Skip && await Task.Run(() => File.Exists(localPath), token)) {
#else
```

It seems like some of this may have come from #234 specifically for UWP scenarios. Nothing that affects cleaning up monikers, but if you agree this sounds like a bug, I can re-summarize as a new issue..

**Comment by FanDjango** [comment]
Especially since "NETSTANDARD" is a synonym for "NETSTANDARD || NET5_0_OR_GREATER currently. But I vote to keep these slightly esoteric task.run()s. I hate these 6 year old sols and would love to remove them and wait for the flak. But....

**Pull request merged**
