### PR TITLE
ResumeUpload: Resume when unexpectedEOF error received while uploading

### PR DESCRIPTION
**Pull request by mrcopperbeard**
After update from version 23.1.0 to 32.2.1 I have started getting errors like [this](https://github.com/robinrodricks/FluentFTP/issues/410) from `FtpClient.UploadAsync` method.

So, maybe it will be correct to resume upload after receiving _unexpectedEOF_ error.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Thanks for this!

**Comment by mrcopperbeard** [comment]
Can you please publish this minor update to Nuget? It seems, the network became less stable last weeks, and our team have a lot of this kind of errors at work

**Comment by robinrodricks** [comment]
I'll do this tomorrow with some improvements.

**Comment by mrcopperbeard** [comment]
Thanks!

**Comment by robinrodricks** [comment]
Released in [32.4.0](https://www.nuget.org/packages/FluentFTP/32.4.0)

#### 32.4.0
  - New: `UploadDirectoryDeleteExcluded` property to control if excluded files are deleted during Upload (thanks [philippjenni](/philippjenni))
  - New: `DownloadDirectoryDeleteExcluded` property to control if excluded files are deleted during Download (thanks [philippjenni](/philippjenni))
  - Fix: Dispose AsyncWaitHandles to stop handle leak in .NET Framework 4.5 (thanks [sdiaman1](/sdiaman1))
  - Fix: Implement proper cancellation support in `UploadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in `DownloadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in FXP `TransferDirectory`
  - Fix: Implement proper cancellation support in recursive `GetListing`
  - Fix: Correctly resume when unexpectedEOF error received during uploading a file (thanks [mrcopperbeard](/mrcopperbeard))
  - Fix: Hide internal properties in `FtpClient` that are not meant to be exposed
  - Fix: Update `IFtpClient` with the latest set of public properties that are meant to be exposed

**Pull request merged**
