### PR TITLE
Expose download speed and eta for a transfer to high level api

### PR DESCRIPTION
**Pull request by n0ix**
Hi,
i thought it would be nice if we can access transfer speed and the eta for transfer via high level api.

I am not sure if all variable names are okay and also if it my way to calculate the transfer speed is best / cleanest way.

apart from this all changes regarding download (i didn't test upload yet) working fine.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Very nice! This is a good contribution.

Could you explain the changes you made to `DownloadFileInternal/Async` and `UploadFileInternal/Async`? They seem kind of extensive and I don't get fully what's happening. I would like to accept this PR but I don't want to break anything.

Also could you rename `ToTransferSpeedHumanReadable` to `TransferSpeedToString`?

**Comment by n0ix** [comment]
Hi, i renamed the function as advised.

Bascially i removed (more or less) duplicate code in these functions and added some variables which i need to calculate the transferspeed and eta.

I added the variable `transferStarted` to know when the transfer started and `bytesProcessed` to track the transfer progress across transfer retries. I just used the code which was there to honor the DownloadRateLimit cause i also need a stopwatch timer.

I also made some modifications to make sure the speed is only throttled if there is a rate limit set.

```
long rateLimitBytes = UploadRateLimit != 0 ? UploadRateLimit * 1024 : 0;
...
 if (rateLimitBytes > 0 && swTime >= 1000) {
...
```

This was previously solved by using a if statement and duplicate code which i mention before.

i hope my explanation of the change is not too confused and you can understand what i changed.

if you have any questions - feel free to ask.

**Comment by robinrodricks** [comment]
Great. Well done.

I'll accept this.

**Comment by robinrodricks** [comment]
Done. Published in FluentFTP [24.0.0](https://www.nuget.org/packages/FluentFTP/24.0.0). 

Please test it and see if everything works as expected.

**Comment by robinrodricks** [comment]
Done. Published in FluentFTP [24.0.0](https://www.nuget.org/packages/FluentFTP/24.0.0). 

Please test it and see if everything works as expected.

**Comment by n0ix** [comment]
Sorry for the last response, just testet it - works as expected ;-)

Thanks.

**Pull request merged**
