### PR TITLE
 Add workaround if a server advertises a non-routeable IP in PASV Mode

### PR DESCRIPTION
**Pull request by n0ix**
In the last days I found an FTP server during tests which (incorrectly) advertises its private IP when opening the passive stream/channel.  So i wrote this quick fix.

### CODE REVIEW

**Comment by robinrodricks** [comment]
No idea, but thanks!

**Comment by robinrodricks** [comment]
Released in [FluentFTP 22](https://www.nuget.org/packages/FluentFTP/22.0.0). Please verify and tell me if it works?

**Comment by n0ix** [comment]
Works as expected - thx for the new release

**Comment by robinrodricks** [comment]
That's awesome.

>

**Pull request merged**
