### PR TITLE
Write exception (optionally) on a new line

### PR DESCRIPTION
**Pull request by FanDjango**
This was suggested at the end of the discussion in #1123

### CODE REVIEW

**Comment by robinrodricks** [comment]
Cool, thanks.

**Comment by jnyrup** [comment]
I wouldn't recommend this.
See e.g. https://martinfowler.com/bliki/FlagArgument.html why having Boolean parameters might be problematic.

How about always printing exceptions on a newline?

**Comment by FanDjango** [comment]
We actually have a far worse place where we do (I mean: I did) this sort of thing: See GetReply(...), or also ReadStaleData. You will shudder when you look at that, I suppose.

> How about always printing exceptions on a newline?

Well, that is probably the best solution then. I wasn't expecting @robinrodricks to merge this mere minutes after opening the PR, LOL and was expecting some discussion, I should have marked it draft.

**Comment by robinrodricks** [comment]
We abuse arguments in this library. Its fine for now as its an internal method and not an API. I guess the bigger problem here is that our API methods have "too many arguments" and should probably use a config object.

**Pull request merged**
