### PR TITLE
Remove an inconsistent whitespace

### PR DESCRIPTION
**Pull request by LeMorrow**

### CODE REVIEW

**Comment by robinrodricks** [comment]
I hope you are using tabs and not spaces for indentation?

**Comment by LeMorrow** [comment]
All I did was to remove one extra whitespace bugging me there, so no tabs should've been deleted/added :smile:

**Comment by LeMorrow** [comment]
Er, I don't know what that second line modification is or how that even got in there, just got in bed but I can revert that change tomorrow, can't really see what it does on phone UI. I meant to remove one space from line 262

**Comment by robinrodricks** [comment]
Don't worry so much. I'll check it out. Thanks.

**Comment by robinrodricks** [comment]
Thanks for your contribution!

**Pull request merged**
