### PR TITLE
#626 UploadDirectory fails for some files "Unable to read data from the transport connection

### PR DESCRIPTION
**Pull request by manuelxmarquez**
PR for #626

### CODE REVIEW

**Comment by robinrodricks** [comment]
Its a good fix, however if the validation fails, you return true? This is weird, anyways I'll accept it and see how it can be changed.

**Comment by manuelxmarquez** [comment]
I'm not sure where you see that change. Can you point it out in the commit?

The diff looks a bit weird but the only change I made was this:

```
		private bool VerifyTransfer(string localPath, string remotePath) {
			try
			{ 
				// Original code
			}
			catch (IOException ex)
			{
				LogStatus(FtpTraceLevel.Warn, "IOException for file " + localPath + " : " + ex.Message);
			
				return false;
			}
		}
```

The original code should function as normal, but suppresses `IOException`s and returns failure. Then the calling method will retry the upload again.

**Comment by manuelxmarquez** [comment]
I ran the code in debug mode and forced a hash failure. Everything functions correctly, here is the log:

> Command:  STOR /appsettings.json
> Response: 150 Opening BINARY mode data connection for appsettings.json.
> Status:   FTPS Authentication Successful
> Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1572223.
> Status:   Disposing FtpSocketStream...
> Response: 226 Transfer complete. 651 bytes transferred. 2.39 KB/sec.
> Status:   Testing connectivity using Socket.Poll()...
> Command:  XMD5 /appsettings.json
> Response: 250 1BD449A9500FB037D194B71EB4A9EBFB
> **Status:   File Verification: FAIL**
> Status:   Retrying due to failed verification.  9 attempts remaining
> Status:   Testing connectivity using Socket.Poll()...
> Command:  SIZE /appsettings.json
> Response: 213 651
> Command:  DELE /appsettings.json
> Response: 250 DELE command successful.
> Command:  EPSV
> Response: 229 Entering Extended Passive Mode (|||40008|)
> Status:   Connecting to [IP]
> Command:  STOR /appsettings.json
> Response: 150 Opening BINARY mode data connection for appsettings.json.
> Status:   FTPS Authentication Successful
> Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1666333.
> Status:   Disposing FtpSocketStream...
> Response: 226 Transfer complete. 651 bytes transferred. 2.40 KB/sec.
> Command:  XMD5 /appsettings.json
> Response: 250 2BD449A9500FB037D194B71EB4A9EBFB
> Status:   File Verification: PASS

Here is an example of IOException in verification:

> Command:  SIZE /Microsoft.Extensions.Configuration.dll
> Response: 213 27512
> Command:  DELE /Microsoft.Extensions.Configuration.dll
> Response: 250 DELE command successful.
> Command:  EPSV
> Response: 229 Entering Extended Passive Mode (|||40007|)
> Status:   Connecting to [IP]
> Command:  STOR /Microsoft.Extensions.Configuration.dll
> Response: 150 Opening BINARY mode data connection for Microsoft.Extensions.Configuration.dll.
> Status:   FTPS Authentication Successful
> Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1566988.
> Status:   Disposing FtpSocketStream...
> Response: 226 Transfer complete. 27,512 bytes transferred. 66.18 KB/sec.
> Command:  XMD5 /Microsoft.Extensions.Configuration.dll
> **Warning:  IOException for file Microsoft.Extensions.Configuration.dll : Unable to read data from the transport connection: An attempt was made to access a socket in a way forbidden by its access permissions.**
> Status:   File Verification: FAIL
> Status:   Retrying due to failed verification.  9 attempts remaining
> Status:   Disposing FtpSocketStream...
> Status:   Connecting to [IP]
> Response: 220 Serv-U FTP Server v15.1 ready...
> Status:   Detected FTP server: ServU
> Command:  AUTH TLS
> Response: 234 AUTH command OK. Initializing SSL connection.
> Status:   FTPS Authentication Successful
> Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1574402.
> Command:  USER ***
> Response: 331 User name okay, need password.
> Command:  PASS ***
> Response: 230 User logged in, proceed.
> Command:  PBSZ 0
> Response: 200 PBSZ command OK. Protection buffer size set to 0.
> Command:  PROT P
> Response: 200 PROT command OK. Using private data connection.
> Command:  FEAT
> Response: 211-Extensions supported
> Response: UTF8
> Response: OPTS MODE;MLST;UTF8
> Response: CLNT
> Response: CSID Name; Version;
> Response: HOST domain
> Response: SITE PSWD;SET;ZONE;CHMOD;MSG;EXEC;HELP
> Response: AUTH TLS;SSL;TLS-C;TLS-P;
> Response: PBSZ
> Response: PROT
> Response: CCC
> Response: SSCN
> Response: RMDA directoryname
> Response: DSIZ
> Response: AVBL
> Response: EPRT
> Response: EPSV
> Response: MODE Z
> Response: THMB BMP|JPEG|GIF|TIFF|PNG max_width max_height pathname
> Response: REST STREAM
> Response: SIZE
> Response: MDTM
> Response: MDTM YYYYMMDDHHMMSS[+-TZ];filename
> Response: MFMT
> Response: MFCT
> Response: MFF Create;Modify;
> Response: XCRC filename;start;end
> Response: XMD5 filename;start;end
> Response: XSHA1 filename;start;end
> Response: XSHA256 filename;start;end
> Response: XSHA512 filename;start;end
> Response: COMB target;source_list
> Response: MLST Type*;Size*;Create;Modify*;Perm;Win32.ea;Win32.dt;Win32.dl
> Response: 211 End (for details use "HELP commmand" where command is the command of interest)
> Status:   Text encoding: System.Text.UTF8Encoding
> Command:  OPTS UTF8 ON
> Response: 200 OPTS UTF8 is set to ON.
> Command:  SYST
> Response: 215 UNIX Type: L8
> Command:  SIZE /Microsoft.Extensions.Configuration.dll
> Response: 213 27512
> Command:  DELE /Microsoft.Extensions.Configuration.dll
> Response: 250 DELE command successful.
> Command:  TYPE I
> Response: 200 Type set to I.
> Command:  EPSV
> Response: 229 Entering Extended Passive Mode (|||40005|)
> Status:   Connecting to [IP]
> Command:  STOR /Microsoft.Extensions.Configuration.dll
> Response: 150 Opening BINARY mode data connection for Microsoft.Extensions.Configuration.dll.
> Status:   FTPS Authentication Successful
> Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1563993.
> Status:   Disposing FtpSocketStream...
> Response: 226 Transfer complete. 27,512 bytes transferred. 74.63 KB/sec.
> Command:  XMD5 /Microsoft.Extensions.Configuration.dll
> Response: 250 3B5D58B60248D941C4EEAAD8BB7ADCFA
> Status:   File Verification: PASS

**Comment by robinrodricks** [comment]
Released in [32.4.6](https://www.nuget.org/packages/FluentFTP/32.4.6)

**Pull request merged**
