### PR TITLE
Added support for the HOST command to be sent after the handshake

### PR DESCRIPTION
**Pull request by dansharpe83**
added a variable in the properties and a command in both Connect and ConnectAsync if the value is set to true

### CODE REVIEW

**Comment by robinrodricks** [comment]
Hi, why is this required? Can you explain what issue it fixes or what it
allows you?

**Comment by dansharpe83** [comment]
We need to connect to an FTP site where the HOST command has to be sent directly after the handshake, i think its to get around where the FTP site resolves to an address rather than ip. without this fix we can't connect to the FTP we use

**Comment by robinrodricks** [comment]
Can you send the logs of a successful connection? See the FAQ in how to get
logs.

**Comment by robinrodricks** [comment]
Thanks Dan!

**Pull request merged**
