### PR TITLE
Enhance the z/OS listing parser to get LRECL (via XDSS) on behalf of user and new Wiki text

### PR DESCRIPTION
**Pull request by FanDjango**
This was one of your suggestions

### CODE REVIEW

**Comment by FanDjango** [comment]
This is the next incremental step to modify the zOS listing parser so that it will do the XDSS command for the user when getting a Non-RECFM=U member listing.

Should have done this right away, but was still learning the internal coding. Sorry.

Next step is a PR to modify the list parser itself to use this new property in its internal processing.

I am trying to keep the PRs small so that one can see the structure of what needs to be changed.

**Comment by FanDjango** [comment]
### **New version for your Wiki**

FluentFTP has extensive support for all variants of IBM z/OS and OS/400 Servers.

### **Realms**
There are 2 realms that FluentFTP supports, and here is some example code for both realms:

**Native z/OS realm:**

```
string zosPath = "'SYS1.'"; // you can also use 'SYS1', both work

FTP_Sess.SetWorkingDirectory(zosPath);
FtpListItem[] list = FTP_Sess.GetListing("", FtpListOption.NoPath);
string fullName = zosPath.Trim('\'').Trim('.') + '.' + list[0].FullName.Remove(0, 1);
```

**USS (linux-like) realm:**

```
string zosPath = "/projects";

FtpListItem[] list = FTP_Sess.GetListing(zosPath);
string fullName = list[0].FullName;
```

**Directory Listings**

When you call GetListing, there are 4 types of listing that are implemented in order to handle variants of the z/OS filesytems:

- List of USS files, is unix-like and handled by the standard FluentFTP unix parser
- List of normal z/OS datasets (non VSAM)
- List of members of partitioned datasets (non load library)
- List of members of partitioned datasets (load library)

[This](https://www.ibm.com/docs/en/zos/2.3.0?topic=subcommands-dir-subcommandobtain-list-directory-entries#dir) IBM document documents the 4 different output formats of the LIST (or DIR) command.

**Example code:**

The following test program demonstrates the differences between the various z/OS filesytems:

```
FtpClient FTP_Sess = new FtpClient();
FTP_Sess.Host = "ftps://xxxxxxx.xxxxx.com";
FTP_Sess.Credentials.UserName = "myuser";
FTP_Sess.Credentials.Password = "secret";
FTP_Sess.ValidateAnyCertificate = false;
FTP_Sess.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);

FTP_Sess.AutoConnect();

// Member Listing non loadlib
string zosPath = "'MYUSER.PRODUCT.CLIB'";
FTP_Sess.SetWorkingDirectory(zosPath);
FtpListItem[] list1 = FTP_Sess.GetListing("", FtpListOption.NoPath);

// Member listing loadlib
zosPath = "'SYS1.V1R3M0.SEAGALT'";
FTP_Sess.SetWorkingDirectory(zosPath);
FtpListItem[] list2 = FTP_Sess.GetListing("", FtpListOption.NoPath);

// Dataset listing
zosPath = "'MYUSER.'";
FTP_Sess.SetWorkingDirectory(zosPath);
FtpListItem[] list3 = FTP_Sess.GetListing("", FtpListOption.NoPath);

// USS file listing
zosPath = "/projects";
FtpListItem[] list4 = FTP_Sess.GetListing(zosPath);

FTP_Sess.Disconnect();
```

**History**

z/OS, a long time ago called MVS, is only one of IBM's four mainframe operating systems (z/OS, z/VM, z/VSE, z/TPF).

In z/OS, using the Communication Server for z/OS, the FTP server can LIST the following types of entries:

- Classic z/OS datasets (many still refer to these as MVS datasets).
- Datasets in other mounted filesystems. These are often referred to as HFS (Hierarchical File System) files, some people refer to these as files in USS (Unix System Services).
- Members of classic z/OS partitioned non-RECFM=U datasets
- Members of classic z/OS partitioned RECFM=U datasets (load libraries)

### **How do I use GetListing?**

**Important note**

The first `GetListing()` of your FTP Client Session will try to determine the listing parser that is needed, unless you **expressly** set this to be the z/OS parser. So, if you do that first `GetListing()` for a unix location, you will erroneously get the parser set to unix. Subsequent `GetListing()` invocations will then fail. Consider setting (forcing) the parser to be z/OS **or** do your first listing in the z/OS dataset realm.

**Alternative #1**

You can use `GetListing()` with an empty path and with `FtpListOption.NoPath`, which causes FluentFTP to use the LIST command without any further parameters - the zOS FTP Server accepts this in the z/OS realm and in the HFS / USS realm.

This in turn means that you must `SetWorkingDirectory()` to go to the desired working directory before doing the `GetListing("", FtpListOption.NoPath`.

```
	string zosPath = "'MYUSER.PRODUCT.CLIB'";
	FTP_Sess.SetWorkingDirectory(zosPath);
	FtpListItem[] list1 = FTP_Sess.GetListing("", FtpListOption.NoPath);
```

This currently means that the `item.FullName` returned by `GetListing(..)` is not correct at this time (because of the `FtpListOption.NoPath`). You need to do it yourself: Use `zosPATH` and depending on the situation of the item (i.e. HFS/USS, Dataset, Member), use slashes, periods, single quotes and parentheses (when the item is a member) to fix up `item.FullName` yourself.

**Alternative #2**

You can use `GetListing()` with a z/OS realm path and **without** `FtpListOption.NoPath`. If the dataset exists, you will get a list with one entry. Otherwise your list will be empty.

To list all datasets below a partly qualified z/OS realm path, you can append `*`. To list all members of a partitioned dataset, use `(*)`.

**How do I set up host file paths?**

Use this to set up host file paths from `GetListing()`results:
**Note** that this example uses **Alternative #1** 

```
FtpClient FTP_Sess = new FtpClient();
FTP_Sess.Host = "ftps://xxxxxxx.xxxxx.com";
FTP_Sess.Credentials.UserName = "myuser";
FTP_Sess.Credentials.Password = "secret";
FTP_Sess.ValidateAnyCertificate = false;
FTP_Sess.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);

FTP_Sess.AutoConnect();

string FTP_Hostfile;

string cwd = "'GEEK.PRODUCTS.LOADLIB'"; // Known to exist, PDS

FTP_Sess.SetWorkingDirectory(cwd);  // Position to there

FtpListItem[] entries = FTP_Sess.GetListing("", FtpListOption.NoPath);

FtpListItem entry = entries[0]; // as an example, take the first entry. 

if (cwd[0] == '\'') // z/OS realm
{
	// Check entry type. If it is not "Dataset", it must be Member or MemberU
	if (FTP_Sess.GetzOSListRealm() != FtpzOSListRealm.Dataset) //
		 // remove quotes, add "(membername from GetListing())" and requote
		FTP_Hostfile = "'" + cwd.Trim('\'') + "(" + entry.Name + ")'";
	else
		// remove quotes, add "(name from GetListing())" and requote
		FTP_Hostfile = "'" + cwd.Trim('\'') + entry.Name + "'";

}
else // HFS / USS realm
	FTP_Hostfile = cwd + entry.Name;

// and now do something with FTP_Hostfile, perhaps download or upload

FTP_Sess.Disconnect();
```

### How do I find out which directory I am in?

To find out where you are, use `GetWorkingDirectory()`.

```
string pwd = FTP_Sess.GetWorkingDirectory();

// pwd examples:
// 'GEEK.PRODUCTS.LOADLIB' This dataset exists.
// 'GEEK.PRODUCTS." This is not an existing dataset. Note the trailing period - it tells us that
// /projects This is a HFS / USS path. Note there are no single quotes, but a slash in front always

```

### **How do I check if I am at the root directory?**

To check if you are already "up at the top", use `IsRoot()`. It knows about z/OS dataset names and would consider a name such as `'SYS1.'` to be a root. Any HLQ (high level qualifier on its own is considered to be root. 

You can use `SetWorkingDirectory("..")` from such a root, but there no way to get a listing from there.

### **How do I detect which realm my current working directory (CWD) is in?**

Get the result of a PWD and check the first character. If it is a single quote, it is the classic z/OS dataset realm, otherwise expect unix-like paths and filenames.

You can use `GetzOSListRealm()` to do exactly that. You will be given `FtpzOSListRealm.Unix`, `FtpzOSListRealm.Dataset`, `FtpzOSListRealm.Member` or `FtpzOSListRealm.MemberU`

**Note** that this tells you how the z/OS GetListing "directory" parser would parse the listing if you were to call `GetListing("", FtpListOption.NoPath)` at that location. So a result of `FtpzOSListRealm.Member` does **not** mean that the current working directory **is a member (of a PDS)**. It rather means, you will get a list of members and that the current working directory is a partitioned dataset.

### **How do I get the file size?**

Since the z/OS CS FTP server does not support the SIZE command to get the file size, here is a quick way to get it (only works if the host file is known to exist):

```
			string path= "'GEEK.PRODUCTS.LOADLIB(FLXWTO)'";

			long size = FTP_Sess.GetzOSFileSize(CWD);
```

It handles all the slash, single-quote, parentheses mangling that is needed for z/OS realms.


### **How is the file size internally calculated?**

The code will supply a size for each entry according to the following table:

**HFS (or USS) realm:**
Size is correct.

**z/OS (aka MVS) datasets:**
_PS_ (i.e. non VSAM, non PDS, just sequential): Size is calculated by multiplying the used tracks by 3390-bytes-per-track (56664 bytes). Depending on the RECFM (consider for example V, VB, VBA), and/or compression, this might overestimate the size by a large amount. Best results on RECFM F, FB, FBA.

_PO_ (i.e. Partitioned Dataset): Size is calculated by multiplying the used tracks by 3390-bytes-per-track (56664 bytes). Depending on the RECFM (consider for example V, VB, VBA), and/or compression, this might overestimate the size by a large amount. Best results on RECFM F, FB, FBA.

**Members of a partitioned dataset:**

_non-RECFM=U_ (for example: RECFM=FB, very common): Size is returned as "number of records" multplied by LRECL.  Depending on the RECFM (consider for example V, VB, VBA), and/or compression, this might overestimate the size by a large amount. Best results on RECFM F, FB, FBA.

LRECL is determined by issuing an internal `XDSS` command (see below).

**Note** that these file sizes depend on ISPF stats stored in the directory of the PDS for each member. These may be missing if the member was created by a non ISPF program. The size will then be reported as being zero. To create stats for such members, use a host-side program that invokes ISPF lib mngmt. service LMSTATS.

_RECFM=U_: Size is returned from the hex length field of the load library listing format and is correct

### **How do I check if a file exists?**
Please refer to PR #765

### **How does GetListing() find the LRECL**
Not tricky at all: Since the introduction of MVSPUT and MVSGET FTP subcommands (from z/OS 2.1 onwards), there is a virtually undocumented command XDSS, which is needed by the functionality of these new commands.

Here is an example:

XDSS 'GEEK.TESTPROG.ASM'
200-LASTREF=2021/10/18 DSEMPTY=FALSE
200 SITE PDSTYPE=PDSE RECFM=FB BLKSIZE=16000 DIRECTORY=1 LRECL=80 PRIMARY=3 SECONDARY=110 TRACKS EATTR=SYSTEM

Note that you will very likely not be able to enter the XDSS FTP subcommand at your favorite ftp client. If you want test it, you need to use it from your FluentFTP session programatically, like in this snippet:

```
long LRECL;

if (entry.Type == FtpFileSystemObjectType.Directory)
{
	string pwd = GetPWD();
	if (pwd[0] == '\'')
	{
		LRECL = 0;
		FtpReply response = FTP_Sess.Execute("XDSS '" + pwd.Trim('\'') + entry.Name + "'");
		if (response.Success)
                        {
				// SITE PDSTYPE=PDSE RECFM=FB BLKSIZE=16000 DIRECTORY=1 LRECL=80 PRIMARY=3 SECONDARY=110 TRACKS EATTR=SYSTEM
				string[] words = response.Message.Split(' ');
				string[] val = words[5].Split('=');
				LRECL = Int64.Parse(val[1]);
			}
		InPDS = true;
	}
}
```

**Comment by robinrodricks** [comment]
Thank you for this excellent update! Wiki updated and PR merged. I will release shortly.

**Comment by robinrodricks** [comment]
I have added a permanent credit note on the [wiki article](https://github.com/robinrodricks/FluentFTP/wiki/IBM-zOS-and-OS-400-Support). Let me know if you want it rewritten.

**Pull request merged**
