### PR TITLE
#387 support for NoopInterval for keeping control socket alive during file transfers

### PR DESCRIPTION
**Pull request by aliquid**

### CODE REVIEW

**Comment by aliquid** [comment]
Ignoring Codacy/PR Quality Review complaint in favor of conformity with existing code.

Complaint;
```csharp
		private int m_noopInterval = 0;
```
Existing code;
```csharp
		private int m_port = 0;
...
		private double m_timeDiff = 0;
...
		private uint m_uploadRateLimit = 0;
...
		private uint m_downloadRateLimit = 0;
```

**Comment by aliquid** [comment]
Ignoring Codacy/PR Quality Review complaint in favor of conformity with existing code.

Complaint;
```csharp
		private int m_noopInterval = 0;
```
Existing code;
```csharp
		private int m_port = 0;
...
		private double m_timeDiff = 0;
...
		private uint m_uploadRateLimit = 0;
...
		private uint m_downloadRateLimit = 0;
```

**Comment by robinrodricks** [comment]
This is awesome. It's been a long outstanding issue and I've literally had no idea how to fix it. I'll review it the moment I get some time. Thanks for your effort/PR. Kudos and wish you a Happy New year!

**Comment by aliquid** [comment]
That should be the last commit from me. Looking forward to the next release! Meantime we are good with the workaround of setting `EnableThreadSafeDataConnections = true`. Thank you!

**Comment by robinrodricks** [comment]
This is very well done indeed. Thank you again kind sir :)

**Comment by robinrodricks** [comment]
Can we set a default value for NoopInterval so its enabled by default? I don't see how it can hurt anything. What value should I keep? 15000?

**Comment by robinrodricks** [comment]
Done. Gone live with 29.0.0:

  - New: Keep control socket alive during long file transfers using NOOP (thanks [aliquid](/aliquid))
  - New: Add `NoopInterval` property to control interval of NOOP commands (thanks [aliquid](/aliquid))

https://www.nuget.org/packages/FluentFTP/29.0.0

**Pull request merged**
