### PR TITLE
Rename FEAT capability MLSD -> MLST

### PR DESCRIPTION
**Pull request by FanDjango**
See #1635 

The capability should be called MLST in the code and not MLSD. Global rename needed.

### CODE REVIEW

**Comment by robinrodricks** [comment]
It looks ok, but it was my understanding that FTP servers can use MLSD and/or MLST?

**Comment by FanDjango** [comment]
In the RFC, it is written: Either both, or none of them. The availability of both is advertised with MLST. An advertisement MLSD does not exist.

But as one can see, some FTP servers ignore the RFC and advertise only MLSD. Some of them then support only MLSD. Some of them support both commands. 

This PR changes only the name MLSD to MLST. It does not change the current logic of allowing both MLST and MLSD advertisements to set the enum "MLST" to true.

It still leaves the decision open, to

1. Adhere to the RFC.

This will hamper **all** none RFC compliant servers in different ways, depending on their deviation.

2. Consider MLST and MLSD advertisements to be synonymous. This is the current implementation, even with this PR applied.

3. Fix #1635 by considering a MLSD advertisement to mean: MLSD command (but not MLST) is supported. This will break an unkown number of servers that need "MLST and MLSD advertisements to be synonymous" (2 above).

Advice?

**Comment by robinrodricks** [comment]
I think this should cover it: - https://github.com/robinrodricks/FluentFTP/issues/1635#issuecomment-2303868824

**Comment by FanDjango** [comment]
Yes. It does.

**Pull request merged**
