### PR TITLE
New API Function FindSrvCmdLimit

### PR DESCRIPTION
**Pull request by FanDjango**
As suggested by you, @robinrodricks, this API function will issue  up to `maxTrys=2000` commands `command="PWD"` with an inter-command delay of `delay=50` to help the user find out the recommended setting of `SslSessionLength` fot this server connection.

Usage:

```cs
	ftpClient.Connect();

	Console.WriteLine("Set SslSessionLength to less than: " + ftpClient.FindSrvCmdLimit());
```

Feel free to rename everything except C# reserved keywords.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Oh wow!

**Comment by robinrodricks** [comment]
How about :

1. AutoSslSessionLength
2. DiscoverSslSessionLength
3. CalcSslSessionLength

**Comment by robinrodricks** [comment]
Is this ok? DiscoverSslSessionLength

**Comment by FanDjango** [comment]
@robinrodricks  Yeah, "Discover" is much better. Thx.

**Comment by FanDjango** [comment]
Closing and Re-Pull... looks cleaner

**Pull request closed without merging**
