### PR TITLE
improve rate control for high level API

### PR DESCRIPTION
**Pull request by wakabayashik**
The original rate control is too rough for me, so I improved the rate control of the high level API.
Note that transferChunkSize may be changed internally to optimize the low rate limit.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Oh great this seems quite advanced. Can you explain the changes you made and why? And whats the hardcoded value for 1 second (1000 ms) used for?

**Comment by wakabayashik** [comment]
1. I deleted the hard-coded 1 second. due to this one second, the FTP client sends the data as fast as possible in the first second, and then sleeps for hundreds of seconds to try to keep low rate limit specified. I don't know what that means in this "hard-coded 1 second".

2. I modified to adjust the chunk size according to rate limit value. rate control is strongly concerned with chunk size. large chunk against low rate limit makes many peeks, adjusted chunk makes it smooth. of course this adjustment can be achieved using exposed "TransferChunkSize", but its hard for users.

3. I modified so that the stopwatch (rate control criteria) is not restarted every loop. restarting of the stopwatch makes a slight deviation from the specified rate limit. Its only be done if actual rate behind the specified rate.

**Comment by robinrodricks** [comment]
Can you explain how this works?

**Comment by wakabayashik** [comment]
here are I/O graphs captured by Wireshark.
please care to the unit of X and Y axis.

1 and 2 => FluentFtp v27.0.3
3 and 4 => FluentFtp improved
5 and 6 => [curl.exe](https://curl.haxx.se/) --limit-rate xxx (for comparison)


1. file size = 210MBytes, UploadRateLimit = 10MBytes/sec, FluentFtp v27.0.3
wireshark_IOGraph_original_10MBps

2. file size = 150MBytes, UploadRateLimit = 500kBytes/sec, FluentFtp v27.0.3
wireshark_IOGraph_original_500kBps
<details><summary>enlarge around peak of 2.</summary>

first peak
wireshark_IOGraph_original_500kBps_peak1

second peak
wireshark_IOGraph_original_500kBps_peak2

last peak
wireshark_IOGraph_original_500kBps_peak3

</details>

3. file size = 210MBytes, UploadRateLimit = 10MBytes/sec, FluentFtp improved
wireshark_IOGraph_improved_10MBps

4. file size = 150MBytes, UploadRateLimit = 500kBytes/sec, FluentFtp improved
wireshark_IOGraph_improved_500kBps

5. file size = 210MBytes, UploadRateLimit = 10MBytes/sec, curl.exe --limit-rate 10M
wireshark_IOGraph_curl_10MBps

6. file size = 150MBytes, UploadRateLimit = 500kBytes/sec, curl.exe --limit-rate 500k
[wireshark_IOGraph_curl_500kBps

---

FluentFtp v27.0.3 has big peaks that violate the limit. Such peaks can cause quality degradation for systems such as VoIP. On the other hand, the improved version and curl.exe are smooth.

actually, I'm using FluentFtpExtension class as workaround with FluentFtp v27.0.3.
[FluentFtpExtension.zip](https://github.com/robinrodricks/FluentFTP/files/3582814/FluentFtpExtension.zip)

```cs
FluentFtpExtension.UploadFileAsyncEx(client,..
```
instread of 
```cs
client.UploadFileAsync(...
```

**Comment by robinrodricks** [comment]
Wow, that's a great improvement. Fantastic work!

**Comment by robinrodricks** [comment]
Published to Nuget. Thanks again!

https://www.nuget.org/packages/FluentFTP/27.1.0

**Pull request merged**
