### PR TITLE
#771 Fixed an issue where the TLS socket would be incorrectly closed,…

### PR DESCRIPTION
**Pull request by michael-hoedl**
... which led to an error with a FileZilla FTP Server

In this PR, the SSL Stream gets closed first. Also, if the method is available, the SSL Stream gets shutdown and will not be disposed in a hard way, which can lead to an error on FileZilla servers. 
The socket will also send a shutdown signal, so that the other endpoint knows, that the connection will be closed.

### CODE REVIEW

**Comment by guyulmaz** [comment]
is this merged and released?

**Comment by robinrodricks** [comment]
@guyulmaz It has been merged as you can see on the top. You can always verify that the fix is present by opening the codebase :

https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Streams/FtpSocketStream.cs#L738

**Comment by robinrodricks** [comment]
@Noxxys and @guyulmaz 

Forgot to release this. Released now!

https://www.nuget.org/packages/FluentFTP/37.0.4

**Comment by Noxxys** [comment]
@robinrodricks thank you, it works in the new version.

**Comment by robinrodricks** [comment]
Awesome!

**Pull request merged**
