### PR TITLE
Fixes #278 Added async versions of methods to IFtpClient

### LINKED ISSUE #278: Consider adding async versions of methods to IFtpClient
**FTP OS:** All

**FTP Server:** All

**Computer OS:** All

Consider adding async versions of methods to `IFtpClient` that return `Task` so the dependency on your client can be fully mocked.

### PR DESCRIPTION
**Pull request by peterfortuin**
This pull request will add the async methods to IFtpClient.
This will fix #278

### CODE REVIEW

**Comment by robinrodricks** [comment]
Tysm for this!

**Comment by peterfortuin** [comment]
Thanks for accepting my pull request. 
Would it be possible that you make a new release with this change included?

**Comment by robinrodricks** [comment]
Yes, I'll make a release today.

**Comment by robinrodricks** [comment]
I tried to build a release it but I'm getting errors with VS 2017 on my PC. The .NET 2.0 version is not building coz it needs a targeting SDK. Until that is resolved I cannot release this. If you can help me I would appreciate it. I'm using Visual Studio 2017 and need a targeting pack for .NET 2.0 but such a thing is [unavailable from MS](https://www.microsoft.com/net/download/visual-studio-sdks).

This is the error:

image

**Comment by robinrodricks** [comment]
I finally managed to get a build going by manually building from VS 2017.

**Comment by robinrodricks** [comment]
Since I built it manually, could you download the latest nuget and please inform if its all ok?

**Comment by peterfortuin** [comment]
Everything seems to work! Thanks a lot!

**Pull request merged**
