### PR TITLE
New FtpRule => FtpRegexRule

### PR DESCRIPTION
**Pull request by n0ix**
I added a simply FtpRule which can check if any of the supplied RegEx pattern matches.

I thought that may be usefull.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Great work! Thanks for this.

**Comment by robinrodricks** [comment]
Hi, some changes:

1. FtpFileNameRegexRule is only meant to check files, correct? So I added a check in `IsAllowed` to ensure only file objects are checked

2. FtpFolderRegexRule is meant to check folder name or folder path? Because the class name suggests you are checking folder name but in the code `item.FullName` is used which is the entire folder path. 

I have fixed both issues, if there is something wrong let me know.

**Comment by n0ix** [comment]
Hi,

thanks for the quick merge and the fixes.

Regarding 3.) - This was intensional, but maybe its better to move this to a sperate Rule (like FtpFolderPathRegexRule  )

**Comment by robinrodricks** [comment]
Released in 31.2.0
  - New: Predefined rules for filtering on file name using regular expressions (thanks [n0ix](/n0ix))
  - New: Predefined rules for filtering on folder name using regular expressions (thanks [n0ix](/n0ix))
  - Fix: Don't calculate ETA and percentage of `FtpProgress` if file size is zero (thanks [Adhara3](/Adhara3))
  - Fix: `GetFilePermissions` should use `GetObjectInfo` instead of `GetListing` to prevent incorrect filepaths

Documented

- https://github.com/robinrodricks/FluentFTP/wiki/Rules#what-kinds-of-rules-are-supported-and-how-do-rules-work
- https://github.com/robinrodricks/FluentFTP/wiki/Class-FtpFileNameRegexRule
- https://github.com/robinrodricks/FluentFTP/wiki/Class-FtpFolderNameRegexRule

Thanks :)

**Pull request merged**
