### PR TITLE
Async Connect Timeouts

### LINKED ISSUE #869: ConnectTimeout not working for ConnectAsync
**FTP OS:** Windows

**Computer OS:** Windows 10 21H2

**FluentFTP Version:** 37.0.0

Target framework: .NET Framework 4.7.2

When calling ConnectAsync() and the host doesn't exist it takes 21 seconds before there is a timeout.
Below is the code I use.
 ```
using (var conn = new FtpClient())
{
    conn.Host = "192.168.0.14";
    conn.Credentials = new NetworkCredential("ftptest", "ftptest");
    conn.ConnectTimeout = 5000;
    await conn.ConnectAsync();
}
```
When calling Connect() the timeout works fine.

**Logs :**

```

# ConnectAsync()
# ConnectAsync()
Status:   Connecting to 192.168.0.14:21
Status:   Connecting to 192.168.0.14:21
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll


# Dispose()
# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

```

### LINKED ISSUE #1035: Connect timeout
**FTP OS:** N/A

**FTP Server:** N/A

**Computer OS:** ? Windows 10

**FluentFTP Version:** ? 42.0.1

**Framework:** .NetFramework 4.8 & .Net 5.0

Different behavior of Connect method (of AsyncFtpClient class) between .NetFramework 4.8 and .Net 5.0:
In .Net 5.0 when trying to connect to a server that doesn't exist, I get a System.TimeoutException and the timeout corresponds to the Config.ConnectTimeout I set.
In .NetFramework 4.8 (using the same code as in .Net 5.0) I get a System.Net.Sockets.SocketException and the timeout is 15 seconds no matter what I put inConfig.ConnectTimeout.

### PR DESCRIPTION
**Pull request by FanDjango**
Fixes #1035.

Also, it brings in some other missing stuff in the async section of Connect.

In the sync section, I tried to make the behaviour for a timeout value of 0 behave the same way as in the async section, which means take the internal socket timeout (about 21 seconds). Otherwise a timeout of 0 would return immediately w/o a connection.

Also, the code to fix #869 was somewhat flaky. Generally, I would refrain from using error texts (in possibly hundreds of different language variants) and try to use socket error codes. Testing for the error text **and** the error code is also quite redundant.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Ok but please keep in mind the required behavior - if there are multiple `addresses[i]`, we are supposed to try each one before breaking with a timeout exception.

**Comment by FanDjango** [comment]
Good catch - I will work on this some more.

**Comment by robinrodricks** [comment]
A suggestion - what if we moved the main connection part into a new subroutine, and then called that from within the "addresses" loop. That way the addresses loop can catch this error and either re-throw it if its the last address, or move to the next address if there are more. So that way it might reduce complication?

**Comment by FanDjango** [comment]
I was thinking in the same direction, only we would need a separate subroutine for sync and for async. But I think it would make the code a lot clearer. Working on it, I am on the road today until the WE and using mobile internet, please stand by.

**Comment by FanDjango** [comment]
SYNC, original code - does not iterate over IPs in the NETSTANDARD case.

 

#if NETSTANDARD

 

                        var args = new SocketAsyncEventArgs {

                             RemoteEndPoint = new IPEndPoint(addresses[i], port)

                        };

                        var connectEvent = new ManualResetEvent(false);

                        args.Completed += (s, e) => { connectEvent.Set(); };

 

                        if (m_socket.ConnectAsync(args)) {

                             if (!connectEvent.WaitOne(connectTimeout)) {

                                   Close();

                                   throw new TimeoutException("Timed out trying to connect!");

                             }

                        }

 

                        if (args.SocketError != SocketError.Success) {

                             throw new SocketException((int)args.SocketError);

                        }

 

                        // only try the first address

                        break;

#else

                        ar = m_socket.BeginConnect(addresses[i], port, null, null);

                        bool success = ar.AsyncWaitHandle.WaitOne(connectTimeout, true);

                        if (!success) {

                             Close();

 

                             // check to see if we're out of addresses, and throw a TimeoutException

                             if (i + 1 == addresses.Length) {

                                   throw new TimeoutException("Timed out trying to connect!");

                             }

                        }

                        else {

                             ar.AsyncWaitHandle.Close();

                             m_socket.EndConnect(ar);

 

                             // we got a connection, break out

                             // of the loop.

                             break;

                        }

 

 

ASYNC was even worse.

 

So you can see that a slight redesign is in order.

 

mit freundlichen Grüßen,

Michael Stiemke ***@***.***)

 

AnSyNova GmbH

Ringstr. 13

85405 Nandlstadt

+49 8756 969 49 79
<http://www.ansynova.com <http://www.ansynova.com/> >

**Pull request closed without merging**
