### PR TITLE
Added some forgotten async methods

### PR DESCRIPTION
**Pull request by taoyouh**

### CODE REVIEW

**Comment by robinrodricks** [comment]
Did you merge the latest changes made by @artiomchi

**Comment by artiomchi** [comment]
Pretty sure there are 4 more methods that both @taoyouh and I missed in our PRs!

Looks safe to merge to me :)

**Comment by robinrodricks** [comment]
@artiomchi any more missing async methods?

**Comment by artiomchi** [comment]
@robinrodricks - I've gone through the library code, and these seem to be the last ones!

**Pull request merged**
