### PR TITLE
Fixed issue with infinite loop, plus other improvements

### PR DESCRIPTION
**Pull request by ejohnsonTKTNET**
Context:

- https://stackoverflow.com/a/18335900/1062614
- https://stackoverflow.com/a/37052176/1062614

### CODE REVIEW

**Comment by ejohnsonTKTNET** [comment]
Seems like the CI is failing due to some external issue?
> Failed   GetPublicFTPServerListing
> Error Message:
>  System.TimeoutException : Timed out trying to connect!

**Comment by jvitkauskas** [comment]
Any news on this?

**Comment by robinrodricks** [comment]
Could you pull master into this branch and re-add your changes? Thanks..

**Comment by robinrodricks** [comment]
Thank you for this!

**Pull request merged**
