### PR TITLE
use logical patterns

### PR DESCRIPTION
**Pull request by jnyrup**
Simplify conditionals with [logical patterns](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#logical-patterns)

### CODE REVIEW

**Comment by FanDjango** [comment]
Nice. How do you find these? Some code analysis tool?

**Comment by robinrodricks** [comment]
Pretty cool, thanks!!

**Comment by jnyrup** [comment]
> Nice. How do you find these? Some code analysis tool?

I closely track what's happening in C#/.NET to become familiar with new syntax and APIs.
For some projects I more aggresively apply different kind of analyzers, e.g. the built-in ones in Visual Studio, [SonarLint](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode) and [Roslynator](https://github.com/JosefPihrt/Roslynator).

For the ones in this PR I simply stumbled upon them I thought they would benefit the project without forcing you two to dig into new _complicated_ syntax.

**Comment by FanDjango** [comment]
> would benefit the project without forcing you two to dig into new complicated syntax.

Yes, of course. Thanks, as I only started with C# / .NET a year and a half ago, I am grateful. And @robinrodricks is very appreciative of any such input, as I have experienced myself.

**Pull request merged**
