### PR TITLE
Demonize NOOP processing for #1410

### PR DESCRIPTION
**Pull request by FanDjango**
Send a random command from { "NOOP", "PWD", "TYPE I", "TYPE A" } when the control connection is idle and no transfer is in progres every NOOPINTERVAL seconds. Use only "NOOP" if a data transfer is running on the data connection.

Use a daemon (task) for this.

Start it on Connect/Authorization ok, stop it when control connection is disposed. Handle reconnects correctly, don't start more than one daemon.

Tell it when GetReply is beginning and when it ends.

Tell it a transfer is running by monitoring SocketStream for Connect/Disconnect of data connection.

It uses NoopInterval

ref. #1410

### CODE REVIEW

**Comment by MisterSausage** [comment]
@FanDjango:
Just started an 18 hour long test using the troublesome Pure-FTPd server I have access to, using your forked code in the THREAD branch, as of commit [fa40f13](https://github.com/FanDjango/FluentFTP/commit/fa40f1361d443e60116783868da23b97f557abc2).

I'll let you know how it goes, and paste in the logs.

**Comment by robinrodricks** [comment]
I was going to do a release now before this daemon, should I or should I wait?

**Comment by MisterSausage** [comment]
@robinrodricks
> I was going to do a release now before this daemon, should I or should I wait?

Just performing a multi-hour test on the daemon at the moment, and it seems to be working very well.

As a user (and as a user that'll use it in production as soon as possible!) I'd suggest waiting a couple of days extra and aiming to include the new daemon code in the next release.

**Comment by robinrodricks** [comment]
Ok sounds good. I'll wait.

**Comment by FanDjango** [comment]
Ok, I am going to close this PR and reopen a clean one.

**Pull request closed without merging**
