### PR TITLE
Implement DownloadPipe

### PR DESCRIPTION
**Pull request by bjornharrtell**
I'm investigating ways to pipe ftp downloads through async logic to avoid waiting for full download or having to store it temporarily.

It looks like simply using System.IO.Pipelines and the stream interface of Pipe would allow this.

I've not put this into practise yet but working on it, but what do you think about this addition to transfer methods?

### CODE REVIEW

**Comment by FanDjango** [comment]
IMHO, a nice idea, if you were to add the integration tests for this to prove the concept and some code samples for the example collection?

**Comment by bjornharrtell** [comment]
@FanDjango actually, I just realized there is no need for this interface as I can just get the stream interface outside and use DownloadStream. Not sure why I didn't see that from the start...

**Comment by FanDjango** [comment]
Well, don't get me wrong, but if it is such an "easy" additional API, that saves the user of the library some lines of code, why not do it? Even if it can be "wrapped" with some code on the users part easily?

**Comment by bjornharrtell** [comment]
@FanDjango initially I wasn't sure stream was an abstraction that would work.. but it does. And that frees you from using a specific pipe implementation (even though System.IO.Pipelines is official/widely used). In any case, I think it's good to avoid dependency on System.IO.Pipelines or other pipeline implementation in this library.

I suppose an example in the "File Transfer" section would be nice. I could possibly try provide a simple one.

**Comment by dbeattie71** [comment]
@bjornharrtell You should be able to use https://github.com/dotnet/Nerdbank.Streams to accomplish this.

**Comment by robinrodricks** [comment]
> Well, don't get me wrong, but if it is such an "easy" additional API, that saves the user of the library some lines of code, why not do it? Even if it can be "wrapped" with some code on the users part easily? 

I am always in agreement with this basic principle. `DownloadPipe` seems to be a nice new API rather than forcing users to use `OpenRead`/`OpenWrite` and those old stream methods that don't have many of the high level functionality.

@bjornharrtell thoughts?

**Comment by robinrodricks** [comment]
Seems interesting

**Comment by bjornharrtell** [comment]
Still no longer see the benefit. The code involved to use a a pipe is simply this:

```csharp
var pipe = new Pipe();
using var writeStream = pipe.Writer.AsStream();
var downloadTask == client.DownloadStream(writeStream, fileName, 0, null, token);
// use pipe to fx. forward to another stream
```

Can't really make it more simple since the resource handling of the writeStream should be the callers responsibility.

**Comment by dbeattie71** [comment]
> Still no longer see the benefit. The code involved to use a a pipe is simply this:
> 
> ```cs
> var pipe = new Pipe();
> using var writeStream = pipe.Writer.AsStream();
> var downloadTask == client.DownloadStream(writeStream, fileName, 0, null, token);
> // use pipe to fx. forward to another stream
> ```
> 
> Can't really make it more simple since the resource handling of the writeStream should be the callers responsibility.

I always used Nerdbank when I wanted to do this, I didn't realize AsStream was added in .NET 8, nice!

**Comment by robinrodricks** [comment]
@bjornharrtell thanks for the code. Can you give me a code sample for UploadStream as well so I can update the wiki with an FAQ on pipes?

**Comment by bjornharrtell** [comment]
Sorry haven't used the upload feature so that would require more time from me than I currently have at the moment.

**Pull request closed without merging**
