### PR TITLE
Log exception

### PR DESCRIPTION
**Pull request by jnyrup**
Follow-up to #1122

### CODE REVIEW

**Comment by FanDjango** [comment]
Hi @jnyrup Happy New Year!

I remember there was a reason for the `.trim()` and it looked nice that way on two lines. But regardless, of course this is nicer code.

**Comment by robinrodricks** [comment]
Ok thanks.

Happy new year to you @FanDjango  and @jnyrup !!

**Comment by jnyrup** [comment]
> I remember there was a reason for the `.trim()` and it looked nice (the output, that is) that way on two lines. But regardless, of course this is nicer code.

Makes sense.
You could change `LogWithPrefix` to include a newline between the custom message and the exception.
```cs
var exceptionMessage = exception is not null ? Environment.NewLine + exception.ToString() : null;
```

**Comment by FanDjango** [comment]
Or even have a bool (with default false) to enable that behaviour

**Pull request merged**
