### PR TITLE
created property RequestSupportedFeatures

### PR DESCRIPTION
**Pull request by nhh-softwarehuset**
added a property in which it is possible to define whether the client should request feature support when calling Connect. This is a neat feature in the case that you have a secured FTP user with limited access to a minimum subset of commands on the ftp server.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Looks good. However can you rename the property to CheckCapabilities?

**Comment by nhh-softwarehuset** [comment]
can be done without any problems ;)

**Comment by robinrodricks** [comment]
You know that many commands will fail because of this right?

**Comment by robinrodricks** [comment]
FluentFTP will think that the server does not support X and those commands will fail..

**Comment by robinrodricks** [comment]
Thanks anyways!

**Comment by WolfspiritM** [comment]
What's with that NCrunch files? Are these really supposed to be there?

**Comment by robinrodricks** [comment]
Which NCrunch files?

>

**Comment by WolfspiritM** [comment]
@robinrodricks This PR added two *.cache files inside the folder "_NCrunch_FluentFTP". I don't think they're supposed to be in the repository.

**Comment by robinrodricks** [comment]
Oh I see. I'll delete those from master.

**Comment by robinrodricks** [comment]
Released in [FluentFTP 22](https://www.nuget.org/packages/FluentFTP/22.0.0). Please verify and tell me if it works?

**Pull request merged**
